name: Build Windows Release

on:
  push:
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    timeout-minutes: 20
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller==6.14.2

    - name: List project structure
      run: |
        Write-Host "=== Projekt-Struktur ==="
        Get-ChildItem -Recurse -Name | Select-Object -First 50
        Write-Host "=== Python-Dateien ==="
        Get-ChildItem -Name "*.py"
        
    - name: Verify main application file
      run: |
        if (Test-Path start_hochzeitsplaner.py) {
          Write-Host "✅ start_hochzeitsplaner.py gefunden"
        } else {
          Write-Host "❌ start_hochzeitsplaner.py nicht gefunden"
          exit 1
        }
    
    - name: Create PyInstaller spec file
      run: |
        @"
        # -*- mode: python ; coding: utf-8 -*-
        
        block_cipher = None
        
        a = Analysis(
            ['start_hochzeitsplaner.py'],
            pathex=[],
            binaries=[],
            datas=[
                ('templates', 'templates'),
                ('static', 'static'),
                ('fonts', 'fonts'),
                ('auth_config.json', '.'),
                ('dyndns_config.json', '.'),
                ('app_config.json', '.'),
                ('hochzeitsplaner_config.json', '.'),
                ('requirements.txt', '.'),
                ('database/schema.sql', 'database'),
                ('database/tischplanung_schema.sql', 'database'),
                ('gunicorn.conf.py', '.'),
            ],
            hiddenimports=[
                'flask',
                'flask_cors',
                'sqlite3',
                'json',
                'datetime',
                'os',
                'sys',
                'logging',
                'functools',
                'werkzeug',
                'jinja2',
                'markupsafe',
                'itsdangerous',
                'click',
                'blinker',
                'email_manager',
                'sqlite_datenmanager',
                'dyndns_manager',
                'config_manager',
                'generate_qr_code',
                'generate_guest_qr_cards',
                'qr_card_generator',
                'pandas',
                'openpyxl',
                'requests',
                'gunicorn',
                'threading',
                'pathlib',
                'zipfile',
                'tempfile',
                'shutil',
                'socket',
                'time',
                'PIL',
                'PIL.Image',
                'PIL.ImageDraw',
                'PIL.ImageFont',
                'qrcode',
                'qrcode.image.pil',
                're',
                'base64',
                'io',
                'hashlib',
                'urllib',
                'urllib.parse',
                'smtplib',
                'email',
                'email.mime',
                'email.mime.text',
                'email.mime.multipart',
                'email.mime.base',
                'email.mime.application',
            ],
            hookspath=[],
            hooksconfig={},
            runtime_hooks=[],
            excludes=[],
            win_no_prefer_redirects=False,
            win_private_assemblies=False,
            cipher=block_cipher,
            noarchive=False,
        )
        
        pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)
        
        exe = EXE(
            pyz,
            a.scripts,
            a.binaries,
            a.zipfiles,
            a.datas,
            [],
            name='hochzeitsplaner',
            debug=False,
            bootloader_ignore_signals=False,
            strip=False,
            upx=True,
            upx_exclude=[],
            runtime_tmpdir=None,
            console=True,
            disable_windowed_traceback=False,
            argv_emulation=False,
            target_arch=None,
            codesign_identity=None,
            entitlements_file=None,
        )
        "@ | Out-File -FilePath "hochzeitsplaner.spec" -Encoding utf8
    
    - name: Build with PyInstaller
      run: |
        Write-Host "=== Starte PyInstaller Build ==="
        pyinstaller hochzeitsplaner.spec --clean --noconfirm
        Write-Host "=== Build abgeschlossen ==="
        Get-ChildItem -Path dist -Recurse
    
    - name: Test built executable
      run: |
        Write-Host "=== Teste die erstellte .exe ==="
        if (Test-Path "dist/hochzeitsplaner.exe") {
          Write-Host "✅ hochzeitsplaner.exe erfolgreich erstellt"
          Get-ChildItem "dist/hochzeitsplaner.exe" | Format-List
        } else {
          Write-Host "❌ hochzeitsplaner.exe nicht gefunden"
          Get-ChildItem -Path dist
          exit 1
        }
    
    - name: Create distribution package
      run: |
        Write-Host "=== Erstelle Distributions-Paket ==="
        New-Item -ItemType Directory -Path "package" -Force
        Copy-Item "dist/hochzeitsplaner.exe" "package/"
        
        # Kopiere Konfigurationsdateien falls vorhanden
        $configFiles = @("auth_config.json", "dyndns_config.json", "app_config.json", "hochzeitsplaner_config.json")
        foreach ($file in $configFiles) {
          if (Test-Path $file) {
            Copy-Item $file "package/" -ErrorAction SilentlyContinue
            Write-Host "📄 $file kopiert"
          }
        }
        
        # Kopiere database-Verzeichnis
        if (Test-Path "database") {
          Copy-Item "database" "package/" -Recurse -ErrorAction SilentlyContinue
          Write-Host "📁 database-Verzeichnis kopiert"
        }
        
        # Erstelle README für das Package
        @"
        # Hochzeitsplaner - Windows Release
        
        ## Installation
        1. Entpacken Sie das ZIP-Archiv
        2. Starten Sie hochzeitsplaner.exe
        3. Beim ersten Start wird eine interaktive Konfiguration durchgeführt
        
        ## Verwendung
        - HTTP: http://localhost:8080
        - Die Anwendung läuft auf Port 8080 mit IPv4/IPv6 Support
        - Zum Beenden: Strg+C im Terminal
        
        ## Datenverzeichnis
        Beim ersten Start können Sie das Datenverzeichnis konfigurieren:
        - Standard: Erstellt 'data/' Verzeichnis neben der .exe
        - Benutzerdefiniert: Eigenen Pfad angeben
        - Vorhandenes Verzeichnis: Bestehende Daten verwenden
        
        Entwickelt für Hochzeitsplanung und Gästemanagement.
        "@ | Out-File -FilePath "package/README.txt" -Encoding utf8
        
        Write-Host "=== Paket-Inhalt ==="
        Get-ChildItem -Path package -Recurse
        
        Write-Host "=== Paket bereit für Upload ==="
    
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: hochzeitsplaner-windows
        path: package/
        retention-days: 90
        # Dateien werden automatisch von GitHub als ZIP gepackt
