name: Build Windows .exe

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Flask==3.0.0 Flask-CORS==4.0.0 pandas==2.1.4 openpyxl==3.1.2 pyinstaller==6.14.2 requests
        
    - name: Prepare launcher file
      run: |
        copy universal_launcher.py launcher.py
    
    - name: Check SSL certificates
      shell: cmd
      run: |
        if exist "ssl_certificate.crt" (
          echo SSL-Zertifikat gefunden: ssl_certificate.crt
        ) else (
          echo SSL-Zertifikat nicht gefunden, erstelle Dummy-Datei
          echo # Dummy SSL Certificate > ssl_certificate.crt
        )
        if exist "ssl_private_key.key" (
          echo SSL-Schlüssel gefunden: ssl_private_key.key
        ) else (
          echo SSL-Schlüssel nicht gefunden, erstelle Dummy-Datei
          echo # Dummy SSL Key > ssl_private_key.key
        )
    
    - name: Build EXE with PyInstaller
      shell: cmd
      run: |
        echo Building Hochzeitsplaner.exe...
        pyinstaller --onefile --windowed --name "Hochzeitsplaner" --add-data "templates;templates" --add-data "static;static" --add-data "data;data" --add-data "dyndns_manager.py;." --add-data "dyndns_config.json;." --add-data "ionos_dyndns_update.py;." --hidden-import=dyndns_manager --hidden-import=requests --hidden-import=flask --hidden-import=werkzeug --hidden-import=jinja2 --distpath dist universal_launcher.py
    
    - name: Verify distribution
      shell: cmd
      run: |
        echo Prüfe erstellte Distribution...
        dir dist
        if exist "dist\Hochzeitsplaner.exe" (
          echo ✅ Hochzeitsplaner.exe erfolgreich erstellt
        ) else (
          echo ❌ Hochzeitsplaner.exe nicht gefunden
          exit 1
        )
    
    - name: Upload distribution artifact
      uses: actions/upload-artifact@v4
      with:
        name: hochzeitsplaner-windows-exe
        path: dist/Hochzeitsplaner.exe
        retention-days: 7
