name: Build Windows .exe

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Flask==3.0.0 Flask-CORS==4.0.0 pandas==2.1.4 openpyxl==3.1.2 pyinstaller==6.14.2 requests
        
    - name: Prepare launcher file
      run: |
        copy universal_launcher.py launcher.py
    
    - name: Check SSL certificates
      shell: cmd
      run: |
        if exist "ssl_certificate.crt" (
          echo SSL-Zertifikat gefunden: ssl_certificate.crt
        ) else (
          echo SSL-Zertifikat nicht gefunden, erstelle Dummy-Datei
          echo # Dummy SSL Certificate > ssl_certificate.crt
        )
        if exist "ssl_private_key.key" (
          echo SSL-Schlüssel gefunden: ssl_private_key.key
        ) else (
          echo SSL-Schlüssel nicht gefunden, erstelle Dummy-Datei
          echo # Dummy SSL Key > ssl_private_key.key
        )
    
    - name: Build executable
      run: |
        pyinstaller --onefile --console --name Hochzeitsplaner launcher.py --add-data "data;data" --add-data "static;static" --add-data "templates;templates" --add-data "auth_config.json;." --add-data "dyndns_config.json;." --add-data "dyndns_manager.py;." --add-data "ionos_dyndns_update.py;." --add-data "requirements.txt;." --add-data "ssl_certificate.crt;." --add-data "ssl_private_key.key;." --hidden-import flask --hidden-import flask_cors --hidden-import pandas --hidden-import openpyxl --hidden-import requests --hidden-import datenmanager --hidden-import dyndns_manager
    
    - name: Create distribution
      shell: cmd
      run: |
        if not exist Distribution mkdir Distribution
        copy "dist\Hochzeitsplaner.exe" "Distribution\"
        echo # Hochzeitsplaner Windows .exe > "Distribution\README.txt"
        echo. >> "Distribution\README.txt"
        echo Doppelklick auf Hochzeitsplaner.exe zum Starten >> "Distribution\README.txt"
        echo. >> "Distribution\README.txt"
        echo Standard-Login: >> "Distribution\README.txt"
        echo Benutzername: admin >> "Distribution\README.txt"
        echo Passwort: hochzeit2025 >> "Distribution\README.txt"
        echo. >> "Distribution\README.txt"
        echo SSL-Zertifikate werden automatisch erkannt falls vorhanden >> "Distribution\README.txt"
        echo DynDNS Manager fuer automatische Domain-Updates integriert >> "Distribution\README.txt"
    
    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: hochzeitsplaner-windows
        path: Distribution/
        retention-days: 90
